%% WRITE2NC - writes a 3D variable to a NetCDF file
% Handles nccreate, ncwrite, and ncwriteatt in one function.
%
% See also
%   NCCREATE, NCWRITE, NCWRITEATT
%
% Last modified
%   2026/02/14, williameclee@arizona.edu (@williameclee)

function write2nc(outputPath, varname, var, options)

    arguments (Input)
        outputPath (1, :) char
        varname (1, :) char
        var
        options.Dimensions (1, :) cell = {}
        options.Attributes (1, :) cell = {}
    end

    if ~isempty(options.Dimensions) && length(options.Dimensions) ~= ndims(var)
        error('Name of dimensions provided does not match variable dimensions (length = %d vs %d).', ...
            length(options.Dimensions), ndims(var));
    elseif ~isempty(options.Dimensions)
        % Pre-allocate dimensions cell array: name and size for each dimension
        dimensions = cell(1, 2 * length(options.Dimensions));

        for iDim = 1:length(options.Dimensions)
            idxName = 2 * iDim - 1;
            idxSize = 2 * iDim;
            dimensions{idxName} = options.Dimensions{iDim};
            dimensions{idxSize} = size(var, iDim);
        end

    else
        % Pre-allocate dimensions cell array when names are autogenerated
        dimensions = cell(1, 2 * ndims(var));

        for iDim = 1:ndims(var)
            idxName = 2 * iDim - 1;
            idxSize = 2 * iDim;
            dimensions{idxName} = sprintf('dim%d', iDim);
            dimensions{idxSize} = size(var, iDim);
        end

    end

    nccreate(outputPath, varname, ...
        "Dimensions", dimensions, ...
        "Datatype", class(var), "Format", 'netcdf4');
    ncwrite(outputPath, varname, var);

    if ~isempty(options.Attributes)

        if mod(length(options.Attributes), 2) ~= 0
            error('Attributes must be provided as name-value pairs (got length = %d).', ...
                length(options.Attributes));
        end

        for iAttr = 1:2:length(options.Attributes)
            attrName = options.Attributes{iAttr};
            attrValue = options.Attributes{iAttr + 1};
            ncwriteatt(outputPath, varname, attrName, attrValue);
        end

    end

end
